import { createFileRoute } from "@tanstack/react-router";
import { AnimatedSection, StaggerContainer, StaggerItem } from "../components/AnimatedSection";
import { FAQSection } from "../components/FAQSection";

export const Route = createFileRoute("/privacy-policy")({
  head: () => ({
    meta: [
      { title: "Privacy Policy — 13L Game | Data Protection & Security" },
      { name: "description", content: "Read 13L Game's privacy policy. Learn how we collect, use, and protect your personal data. 13L Game is committed to user privacy and data security." },
      { property: "og:title", content: "Privacy Policy — 13L Game" },
      { property: "og:description", content: "How 13L Game protects your data and privacy." },
      { name: "keywords", content: "13l game privacy policy, 13l game data protection, 13l game security" },
    ],
  }),
  component: PrivacyPolicyPage,
});

const sections = [
  { title: "1. Introduction", content: "Welcome to 13L Game. This Privacy Policy explains in detail how we collect, use, disclose, and safeguard your information when you visit our website 13l.video and use our gaming services. At 13L Game, we are deeply committed to protecting your personal information and your right to privacy. We understand that you are trusting us with your data, and we take that responsibility with the utmost seriousness. By using 13L Game, you agree to the collection and use of information in accordance with this policy. This Privacy Policy applies to all users of the 13L Game platform, including visitors, registered players, VIP members, and anyone who interacts with our services in any capacity." },
  { title: "2. Information We Collect", content: "When you register on 13L Game, login to your account, or use our services, we collect several types of information to provide and improve your gaming experience. This includes your mobile phone number used for account creation, verification, and account recovery. We store your account credentials — your password is encrypted using advanced cryptographic hashing algorithms, meaning even our own team cannot access your actual password. We collect device information including your browser type, operating system, screen resolution, and device identifiers to optimize the gaming experience for your specific setup. Your IP address and approximate geographic location help us provide region-appropriate services and detect suspicious activity. We track game activity, including which games you play, bet amounts, outcomes, and session durations, to improve our services and detect irregularities. Transaction history including deposits, withdrawals, and bonus redemptions is maintained for financial record-keeping and fraud prevention. We may also collect information you voluntarily provide through customer support interactions, community participation, or feedback submissions." },
  { title: "3. How We Use Your Information", content: "13L Game uses the collected information for several essential purposes. Account management: we use your mobile number and credentials to create, maintain, and secure your 13L Game account, enabling you to login and access all platform features. Transaction processing: your financial information is used to process deposits, withdrawals, and bonus redemptions securely and efficiently. Customer support: when you contact our support team, we use your account and activity data to understand your issue and provide accurate, timely assistance. Platform improvement: aggregated and anonymized usage data helps us understand how players interact with 13L Game, which games are most popular, and where we can improve the user experience. Communication: we send important notifications about your account, including transaction confirmations, security alerts, and 13L Game updates. We may also inform you about new games, promotions, and gift codes. Security and fraud prevention: we analyze patterns in account activity, login behavior, and transactions to detect and prevent unauthorized access, fraud, and abuse. Legal compliance: we may use your information to comply with applicable laws, regulations, and legal processes." },
  { title: "4. Data Security", content: "13L Game implements comprehensive, industry-standard security measures to protect your personal information and financial data. All data transmitted between your device and our servers is encrypted using 256-bit SSL/TLS encryption — the same technology used by major banks and financial institutions worldwide. Your password is stored using advanced cryptographic hashing (bcrypt), making it impossible to reverse-engineer even if our database were compromised. Payment transactions are processed through PCI-DSS compliant secure gateways that meet the highest international standards for financial data security. We conduct regular security audits, vulnerability assessments, and penetration testing to identify and address potential threats before they can affect our users. Access to user data within our organization is strictly controlled — only authorized personnel with specific job responsibilities have access, and all access is logged and monitored. Our servers are hosted in secure data centers with physical security measures, redundant systems, and disaster recovery capabilities. We maintain an incident response plan that allows us to respond quickly and effectively to any security event." },
  { title: "5. Information Sharing", content: "13L Game does not sell, rent, or trade your personal information to third parties for marketing purposes. We value your trust and treat your data with the highest level of respect. We may share information in limited circumstances: with trusted service providers who assist in operating our platform, such as hosting providers, payment processors, and analytics services — these providers are contractually bound to protect your data and can only use it for the specific services they provide to us. With payment gateways for the sole purpose of processing your deposit and withdrawal transactions securely. With law enforcement or regulatory authorities when required by law, subpoena, or court order, or when we believe in good faith that disclosure is necessary to protect our rights, your safety, or the safety of others. With business partners, but only with your explicit, informed consent. In the event of a merger, acquisition, or sale of assets, your information may be transferred to the new entity, but we will notify you and ensure the same level of protection continues." },
  { title: "6. Cookies and Tracking Technologies", content: "13L Game uses cookies and similar tracking technologies to enhance your experience on our platform. Session cookies maintain your login state so you don't need to re-authenticate on every page. Preference cookies remember your settings, such as language and display preferences, so your 13L Game experience is personalized. Analytics cookies help us understand how users navigate the platform, which pages are most visited, and where users encounter difficulties — this data is aggregated and anonymized to improve our services. Security cookies help us detect unusual activity and protect your account from unauthorized access. You can control cookie settings through your browser preferences. However, disabling certain cookies may affect the functionality of 13L Game, particularly login session management. We do not use cookies for third-party advertising purposes." },
  { title: "7. Your Rights and Choices", content: "As a 13L Game user, you have several rights regarding your personal data. You have the right to access your personal information — you can view and download the data we hold about you through your account settings or by contacting support. You can request correction of any inaccurate or outdated information in your profile. You have the right to request deletion of your account and all associated personal data, subject to legal retention requirements for financial records. You can opt out of promotional communications at any time while still receiving essential account notifications. You have the right to data portability — we can provide your data in a commonly used, machine-readable format. You can withdraw consent for data processing where consent is the legal basis, though this may affect your ability to use certain 13L Game features. To exercise any of these rights, contact our support team through the in-app chat or our official Telegram channels." },
  { title: "8. Data Retention", content: "13L Game retains your personal information for as long as your account is active and as needed to provide our services. When you request account deletion, we remove your personal information within 30 days, except for certain data that must be retained for legal, regulatory, or fraud prevention purposes. Financial transaction records may be retained for up to 7 years to comply with applicable financial regulations and tax requirements. Aggregated and anonymized data that cannot be linked back to you may be retained indefinitely for analytics and platform improvement purposes. Inactive accounts may be subject to data cleanup after extended periods of inactivity, with prior notification sent to your registered mobile number." },
  { title: "9. Children's Privacy", content: "13L Game is strictly intended for adults aged 18 and above. We do not knowingly collect, store, or process personal information from individuals under the age of 18. Our registration process requires users to confirm they are of legal age. If we discover that a minor has provided personal information or created an account on 13L Game, we will immediately delete the account and all associated data. We encourage parents and guardians to monitor their children's online activities and ensure they do not access age-restricted platforms like 13L Game." },
  { title: "10. International Users", content: "13L Game is primarily operated in India. If you access our services from outside India, please be aware that your data may be transferred to and processed in India. By using 13L Game, you consent to this transfer. We ensure that all data, regardless of origin, is protected according to the standards described in this Privacy Policy. We strive to comply with applicable data protection laws in all jurisdictions where our users are located." },
  { title: "11. Changes to This Policy", content: "13L Game may update this Privacy Policy from time to time to reflect changes in our practices, technology, legal requirements, or platform features. When significant changes are made, we will notify users through the platform, via SMS to registered numbers, or through our official Telegram channels. The updated policy will include a new 'Last Updated' date. We encourage users to review this Privacy Policy periodically. Continued use of 13L Game after changes are posted constitutes acceptance of the updated policy." },
  { title: "12. Contact Us", content: "If you have questions, concerns, or requests related to this Privacy Policy or how 13L Game handles your personal data, we encourage you to reach out through any of our official channels. You can contact us through the in-app live chat for immediate assistance, through our official Telegram channel for community-based support, or by reaching out to the Veeranjan Solution team via Telegram at t.me/veeranjan_solutions. We aim to respond to all privacy-related inquiries within 48 hours." },
];

const privacyFaqs = [
  { question: "How does 13L Game protect my personal data?", answer: "13L Game uses 256-bit SSL/TLS encryption for all data transmission, bcrypt password hashing, PCI-DSS compliant payment processing, regular security audits, strict internal access controls, and secure data center hosting. Your personal and financial data is protected by the same level of security used by major banks and financial institutions." },
  { question: "Does 13L Game sell my information to third parties?", answer: "No. 13L Game does not sell, rent, or trade your personal information to any third party for marketing or any other purpose. We only share data with essential service providers (hosting, payments) who are contractually bound to protect it, and with law enforcement when legally required." },
  { question: "Can I delete my 13L Game account and data?", answer: "Yes. You can request complete deletion of your 13L Game account and personal data by contacting our support team. Your data will be removed within 30 days, except for financial records that must be retained for legal compliance purposes." },
  { question: "What cookies does 13L Game use?", answer: "13L Game uses session cookies for login management, preference cookies for personalization, analytics cookies for platform improvement, and security cookies for fraud detection. We do not use cookies for third-party advertising. You can manage cookie settings through your browser." },
];

function PrivacyPolicyPage() {
  return (
    <div className="pt-20 overflow-hidden">
      <section className="py-16 px-4" style={{ background: "var(--gradient-hero)" }}>
        <AnimatedSection className="mx-auto max-w-4xl text-center">
          <h1 className="text-4xl font-extrabold md:text-5xl">Privacy Policy</h1>
          <p className="mt-3 text-muted-foreground">Last updated: April 2026</p>
          <div className="section-divider mt-4" />
        </AnimatedSection>
      </section>

      <section className="py-16 px-4">
        <div className="mx-auto max-w-3xl space-y-8">
          {sections.map((section, i) => (
            <AnimatedSection key={section.title} delay={i * 0.05}>
              <div className="gaming-card">
                <h2 className="text-xl font-bold text-foreground mb-3">{section.title}</h2>
                <p className="text-muted-foreground leading-relaxed">{section.content}</p>
              </div>
            </AnimatedSection>
          ))}
        </div>
      </section>

      <FAQSection title="Privacy Policy — FAQ" subtitle="Quick answers to common questions about data protection on 13L Game." faqs={privacyFaqs} />
    </div>
  );
}
