/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as HowToPlayRouteImport } from './routes/how-to-play'
import { Route as GiftCodesRouteImport } from './routes/gift-codes'
import { Route as GamesRouteImport } from './routes/games'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as AboutRouteImport } from './routes/about'
import { Route as R13lgameRegisterRouteImport } from './routes/13lgame-register'
import { Route as R13lgameLoginRouteImport } from './routes/13lgame-login'
import { Route as R13lgameGiftcodeRouteImport } from './routes/13lgame-giftcode'
import { Route as R13lgameDownloadRouteImport } from './routes/13lgame-download'
import { Route as IndexRouteImport } from './routes/index'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToPlayRoute = HowToPlayRouteImport.update({
  id: '/how-to-play',
  path: '/how-to-play',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftCodesRoute = GiftCodesRouteImport.update({
  id: '/gift-codes',
  path: '/gift-codes',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const R13lgameRegisterRoute = R13lgameRegisterRouteImport.update({
  id: '/13lgame-register',
  path: '/13lgame-register',
  getParentRoute: () => rootRouteImport,
} as any)
const R13lgameLoginRoute = R13lgameLoginRouteImport.update({
  id: '/13lgame-login',
  path: '/13lgame-login',
  getParentRoute: () => rootRouteImport,
} as any)
const R13lgameGiftcodeRoute = R13lgameGiftcodeRouteImport.update({
  id: '/13lgame-giftcode',
  path: '/13lgame-giftcode',
  getParentRoute: () => rootRouteImport,
} as any)
const R13lgameDownloadRoute = R13lgameDownloadRouteImport.update({
  id: '/13lgame-download',
  path: '/13lgame-download',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/13lgame-download': typeof R13lgameDownloadRoute
  '/13lgame-giftcode': typeof R13lgameGiftcodeRoute
  '/13lgame-login': typeof R13lgameLoginRoute
  '/13lgame-register': typeof R13lgameRegisterRoute
  '/about': typeof AboutRoute
  '/disclaimer': typeof DisclaimerRoute
  '/games': typeof GamesRoute
  '/gift-codes': typeof GiftCodesRoute
  '/how-to-play': typeof HowToPlayRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/13lgame-download': typeof R13lgameDownloadRoute
  '/13lgame-giftcode': typeof R13lgameGiftcodeRoute
  '/13lgame-login': typeof R13lgameLoginRoute
  '/13lgame-register': typeof R13lgameRegisterRoute
  '/about': typeof AboutRoute
  '/disclaimer': typeof DisclaimerRoute
  '/games': typeof GamesRoute
  '/gift-codes': typeof GiftCodesRoute
  '/how-to-play': typeof HowToPlayRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/13lgame-download': typeof R13lgameDownloadRoute
  '/13lgame-giftcode': typeof R13lgameGiftcodeRoute
  '/13lgame-login': typeof R13lgameLoginRoute
  '/13lgame-register': typeof R13lgameRegisterRoute
  '/about': typeof AboutRoute
  '/disclaimer': typeof DisclaimerRoute
  '/games': typeof GamesRoute
  '/gift-codes': typeof GiftCodesRoute
  '/how-to-play': typeof HowToPlayRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/13lgame-download'
    | '/13lgame-giftcode'
    | '/13lgame-login'
    | '/13lgame-register'
    | '/about'
    | '/disclaimer'
    | '/games'
    | '/gift-codes'
    | '/how-to-play'
    | '/privacy-policy'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/13lgame-download'
    | '/13lgame-giftcode'
    | '/13lgame-login'
    | '/13lgame-register'
    | '/about'
    | '/disclaimer'
    | '/games'
    | '/gift-codes'
    | '/how-to-play'
    | '/privacy-policy'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/13lgame-download'
    | '/13lgame-giftcode'
    | '/13lgame-login'
    | '/13lgame-register'
    | '/about'
    | '/disclaimer'
    | '/games'
    | '/gift-codes'
    | '/how-to-play'
    | '/privacy-policy'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R13lgameDownloadRoute: typeof R13lgameDownloadRoute
  R13lgameGiftcodeRoute: typeof R13lgameGiftcodeRoute
  R13lgameLoginRoute: typeof R13lgameLoginRoute
  R13lgameRegisterRoute: typeof R13lgameRegisterRoute
  AboutRoute: typeof AboutRoute
  DisclaimerRoute: typeof DisclaimerRoute
  GamesRoute: typeof GamesRoute
  GiftCodesRoute: typeof GiftCodesRoute
  HowToPlayRoute: typeof HowToPlayRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-play': {
      id: '/how-to-play'
      path: '/how-to-play'
      fullPath: '/how-to-play'
      preLoaderRoute: typeof HowToPlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift-codes': {
      id: '/gift-codes'
      path: '/gift-codes'
      fullPath: '/gift-codes'
      preLoaderRoute: typeof GiftCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/13lgame-register': {
      id: '/13lgame-register'
      path: '/13lgame-register'
      fullPath: '/13lgame-register'
      preLoaderRoute: typeof R13lgameRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/13lgame-login': {
      id: '/13lgame-login'
      path: '/13lgame-login'
      fullPath: '/13lgame-login'
      preLoaderRoute: typeof R13lgameLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/13lgame-giftcode': {
      id: '/13lgame-giftcode'
      path: '/13lgame-giftcode'
      fullPath: '/13lgame-giftcode'
      preLoaderRoute: typeof R13lgameGiftcodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/13lgame-download': {
      id: '/13lgame-download'
      path: '/13lgame-download'
      fullPath: '/13lgame-download'
      preLoaderRoute: typeof R13lgameDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R13lgameDownloadRoute: R13lgameDownloadRoute,
  R13lgameGiftcodeRoute: R13lgameGiftcodeRoute,
  R13lgameLoginRoute: R13lgameLoginRoute,
  R13lgameRegisterRoute: R13lgameRegisterRoute,
  AboutRoute: AboutRoute,
  DisclaimerRoute: DisclaimerRoute,
  GamesRoute: GamesRoute,
  GiftCodesRoute: GiftCodesRoute,
  HowToPlayRoute: HowToPlayRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
